env_name: NH_tree
dynamic_name: Multirotor

navigation_3d: false
using_velocity_state: false
perception: depth  # depth, lgmd, vector

algo: PPO
total_timesteps: 100000

policy_name: mlp
net_arch: [64, 32, 16]
activation_function: tanh
cnn_feature_num: 25

keyboard_debug: false
generate_q_map: true
q_map_save_steps: 10000

environment:
  max_depth_meters: 15
  screen_height: 60
  screen_width: 90
  crash_distance: 2
  accept_radius: 2

multirotor:
  dt: 0.1
  acc_xy_max: 2.0
  v_xy_max: 5
  v_xy_min: 0.5
  v_z_max: 2.0
  yaw_rate_max_deg: 30.0

DRL:
  gamma: 0.99
  learning_rate: 0.001
  learning_starts: 2000
  buffer_size: 50000
  batch_size: 256
  train_freq: 100
  gradient_steps: 100
  action_noise_sigma: 0.1
